### PR TITLE
Do some clean up and add basic controller support

### PR DESCRIPTION
**Pull request by aaronsnig501**

### CODE REVIEW

**Review by yoniLavi — CHANGES_REQUESTED** [review]
Very cool!
Just one question - is there a reason for the file duplication (route-config.js - routeConfig.js and page-render.js - pageRender.js)? Did you intend for one to be a skeleton, and the other the actual code?

**Comment by aaronsnig501** [comment]
No idea how they got in there. I thought I'd renamed them. I only wanted the hyphenated files in there. I'll remove the duplicates and re-submit :)

**Comment by yoniLavi** [comment]
Thanks :)

**Comment by aaronsnig501** [comment]
No probs :) I'll be sure to make some more contributions too!

**Pull request merged**
